package ua.gradsoft.jungle.gwt.util.client.gxt;

/**
 *Events, generated by BeanModelSelectionWidget
 * @author rssh
 */
public interface BeanModelSelectionEvents {

    public static final int ADD = 1;
    public static final int DELETE = 2;
    public static final int SELECT = 3;


}
