/* Generated By:JavaCC: Do not edit this line. CPPPParserConstants.java */
package ua.gradsoft.cppp.parse;

public interface CPPPParserConstants {

  int EOF = 0;
  int WS = 18;
  int WSP = 19;
  int WSCONTINUE = 20;
  int NEWLINE = 21;
  int CE_INTEGER = 22;
  int ID = 23;
  int PUNCT = 24;
  int LESS = 25;
  int GREATER = 26;
  int LOGICAL_OR = 27;
  int LOGICAL_AND = 28;
  int BIT_OR = 29;
  int BIT_AND = 30;
  int EQ = 31;
  int NEQ = 32;
  int LESS_EQ = 33;
  int GREATER_EQ = 34;
  int LEFT_SHIFT = 35;
  int RIGHT_SHIFT = 36;
  int PLUS = 37;
  int MINUS = 38;
  int MULTIPLY = 39;
  int DIVIDE = 40;
  int MOD = 41;
  int BIT_NEGATE = 42;
  int LOGICAL_NOT = 43;
  int NN = 44;
  int CHARACTER = 45;
  int STRING = 46;
  int ONE_QUOTE = 47;
  int C_COMMENT_BEGIN = 48;
  int CPP_COMMENT = 49;
  int XML_COMMENT_BEGIN = 50;
  int FCHAR = 51;
  int QCHAR = 52;
  int C_COMMENT_END = 53;
  int XML_COMMENT_END = 55;

  int DEFAULT = 0;
  int FILENAME_1 = 1;
  int FILENAME_2 = 2;
  int IN_C_COMMENT = 3;
  int IN_XML_COMMENT = 4;

  String[] tokenImage = {
    "<EOF>",
    "\"#\"",
    "\"if\"",
    "\"ifdef\"",
    "\"ifndef\"",
    "\"elif\"",
    "\"else\"",
    "\"endif\"",
    "\"define\"",
    "\"undef\"",
    "\"include\"",
    "\"line\"",
    "\"error\"",
    "\"pragma\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"defined\"",
    "<WS>",
    "<WSP>",
    "<WSCONTINUE>",
    "<NEWLINE>",
    "<CE_INTEGER>",
    "<ID>",
    "<PUNCT>",
    "\"<\"",
    "\">\"",
    "\"||\"",
    "\"&&\"",
    "\"|\"",
    "\"&\"",
    "\"==\"",
    "\"!=\"",
    "\"<=\"",
    "\">=\"",
    "\"<<\"",
    "\">>\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"~\"",
    "\"!\"",
    "\"##\"",
    "<CHARACTER>",
    "<STRING>",
    "<ONE_QUOTE>",
    "<C_COMMENT_BEGIN>",
    "<CPP_COMMENT>",
    "\"<!--\"",
    "<FCHAR>",
    "<QCHAR>",
    "<C_COMMENT_END>",
    "<token of kind 54>",
    "<XML_COMMENT_END>",
    "<token of kind 56>",
  };

}
