/* Generated By:JavaCC: Do not edit this line. CEXPRParserConstants.java */
package ua.gradsoft.cppp.parse;

public interface CEXPRParserConstants {

  int EOF = 0;
  int NEWLINE = 6;
  int OCTALINT = 7;
  int DECIMALINT = 8;
  int HEXADECIMALINT = 9;
  int DOUBLE_LITERAL = 10;
  int EXPONENT = 11;
  int ID = 12;
  int PUNCT = 13;
  int LESS = 14;
  int GREATER = 15;
  int LOGICAL_OR = 16;
  int LOGICAL_AND = 17;
  int BIT_OR = 18;
  int BIT_AND = 19;
  int EQ = 20;
  int NEQ = 21;
  int LESS_EQ = 22;
  int GREATER_EQ = 23;
  int LEFT_SHIFT = 24;
  int RIGHT_SHIFT = 25;
  int PLUS = 26;
  int MINUS = 27;
  int MULTIPLY = 28;
  int DIVIDE = 29;
  int MOD = 30;
  int BIT_NEGATE = 31;
  int LOGICAL_NOT = 32;
  int NN = 33;
  int CHARACTER = 34;
  int STRING = 35;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\"(\"",
    "\")\"",
    "\"defined\"",
    "\",\"",
    "<token of kind 5>",
    "<NEWLINE>",
    "<OCTALINT>",
    "<DECIMALINT>",
    "<HEXADECIMALINT>",
    "<DOUBLE_LITERAL>",
    "<EXPONENT>",
    "<ID>",
    "<PUNCT>",
    "\"<\"",
    "\">\"",
    "\"||\"",
    "\"&&\"",
    "\"|\"",
    "\"&\"",
    "\"==\"",
    "\"!=\"",
    "\"<=\"",
    "\">=\"",
    "\"<<\"",
    "\">>\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"~\"",
    "\"!\"",
    "\"##\"",
    "<CHARACTER>",
    "<STRING>",
  };

}
